// Command netcafeshopgen extracts the N point (PC방 포인트) shop prices from
// the client's mhfdat.bin into a Go lookup table. The client lists and prices
// this shop itself and sends unit price x quantity as PointCost
// (MsgMhfAcquireCafeItem), so the server needs the prices to check it.
//
// mhfdat holds three tables of this record shape back to back. The one the
// N point shop shows is the cheapest; the other two list mostly higher prices
// for overlapping items. Keeping each item's lowest price over all three
// rejects underpayment without refusing a purchase made from any of them.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"erupe-ce/common/decryption"
)

// shopRecordSize is one shop entry: u16 item ID, u16 zero, u32 unit price,
// u8 tab, u8 sub-tab, u8 quantity, u8 zero (little-endian).
const shopRecordSize = 12

// minShopRecords keeps unrelated short runs of plausible records out.
const minShopRecords = 1000

type shopRun struct {
	offset, count int
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(args []string) error {
	flags := flag.NewFlagSet("netcafeshopgen", flag.ContinueOnError)
	flags.SetOutput(os.Stderr)
	inputPath := flags.String("input", "", "path to the client's dat/mhfdat.bin")
	outputPath := flags.String("output", "", "path to netcafe_shop_generated.go")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return fmt.Errorf("unexpected positional arguments: %s", strings.Join(flags.Args(), " "))
	}
	if *inputPath == "" || *outputPath == "" {
		return errors.New("-input and -output are required")
	}
	raw, err := os.ReadFile(*inputPath)
	if err != nil {
		return err
	}
	data, err := decodeMhfdat(raw)
	if err != nil {
		return err
	}
	prices, runs, err := extractShopPrices(data)
	if err != nil {
		return err
	}
	sum := sha256.Sum256(raw)
	source, err := generate(prices, runs, strings.ToUpper(hex.EncodeToString(sum[:])))
	if err != nil {
		return err
	}
	return os.WriteFile(*outputPath, source, 0o644)
}

func decodeMhfdat(raw []byte) ([]byte, error) {
	data := raw
	if bytes.HasPrefix(data, []byte("ecd\x1a")) {
		var err error
		if data, err = decryption.DecodeECD(data); err != nil {
			return nil, fmt.Errorf("decode ECD: %w", err)
		}
	}
	return decryption.UnpackSimple(data), nil
}

func validShopRecord(data []byte, offset int) bool {
	if offset < 0 || offset+shopRecordSize > len(data) {
		return false
	}
	r := data[offset : offset+shopRecordSize]
	id := binary.LittleEndian.Uint16(r[0:])
	price := binary.LittleEndian.Uint32(r[4:])
	return id != 0 && id < 0x8000 && binary.LittleEndian.Uint16(r[2:]) == 0 &&
		price != 0 && price <= 1000000 && r[8] <= 6 && r[9] < 16 && r[10] == 1 && r[11] == 0
}

// findShopRuns returns every run of at least minShopRecords valid records.
func findShopRuns(data []byte) []shopRun {
	var runs []shopRun
	for offset := 0; offset+shopRecordSize <= len(data); {
		if !validShopRecord(data, offset) || validShopRecord(data, offset-shopRecordSize) {
			offset += 2
			continue
		}
		count := 0
		for validShopRecord(data, offset+count*shopRecordSize) {
			count++
		}
		if count >= minShopRecords {
			runs = append(runs, shopRun{offset, count})
			offset += count * shopRecordSize
		} else {
			offset += 2
		}
	}
	return runs
}

// extractShopPrices returns each item's lowest unit price over all tables.
func extractShopPrices(data []byte) (map[uint16]uint32, []shopRun, error) {
	runs := findShopRuns(data)
	if len(runs) == 0 || len(runs) > 4 {
		return nil, nil, fmt.Errorf("expected 1-4 shop tables in mhfdat, found %d: %v", len(runs), runs)
	}
	prices := map[uint16]uint32{}
	for _, run := range runs {
		for i := 0; i < run.count; i++ {
			r := data[run.offset+i*shopRecordSize:]
			id := binary.LittleEndian.Uint16(r[0:])
			price := binary.LittleEndian.Uint32(r[4:])
			if known, ok := prices[id]; !ok || price < known {
				prices[id] = price
			}
		}
	}
	return prices, runs, nil
}

func generate(prices map[uint16]uint32, runs []shopRun, sourceSHA string) ([]byte, error) {
	ids := make([]int, 0, len(prices))
	for id := range prices {
		ids = append(ids, int(id))
	}
	sort.Ints(ids)
	tables := make([]string, len(runs))
	for i, run := range runs {
		tables[i] = fmt.Sprintf("0x%X (%d records)", run.offset, run.count)
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/netcafeshopgen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: client dat/mhfdat.bin, shop tables at decoded offsets %s\n", strings.Join(tables, ", "))
	fmt.Fprintf(&b, "// Source SHA-256: %s\n\npackage channelserver\n\n", sourceSHA)
	b.WriteString("// netcafeShopMinPrices maps item ID to the lowest unit N point price the\n// client lists for it.\n")
	b.WriteString("var netcafeShopMinPrices = map[uint16]uint32{\n")
	for _, id := range ids {
		fmt.Fprintf(&b, "\t0x%04X: %d,\n", id, prices[uint16(id)])
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}
